package edu.mum.cs.cs425.eregistrar.model;

import java.time.LocalDate;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

/**
 * JPA entity that represents a Student registration record.
 */
@Entity
@Table(name = "student")
public class Student {

	// Primary key. Auto-generated by the database when a new student is registered.
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "student_id")
	private Long studentId;

	@NotBlank(message = "Student number is required")
	@Column(name = "student_number", nullable = false, unique = true)
	private String studentNumber;

	@NotBlank(message = "First name is required")
	@Column(name = "first_name", nullable = false)
	private String firstName;

	// Optional.
	@Column(name = "middle_name")
	private String middleName;

	@NotBlank(message = "Last name is required")
	@Column(name = "last_name", nullable = false)
	private String lastName;

	// Optional. Double (object) so it can be null.
	@Column(name = "cgpa")
	private Double cgpa;

	@NotNull(message = "Enrollment date is required")
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
	@Column(name = "enrollment_date", nullable = false)
	private LocalDate enrollmentDate;

	// Required. Stored as the text "Yes" or "No" (matches the spec).
	@NotBlank(message = "Please indicate whether the student is international")
	@Column(name = "is_international", nullable = false)
	private String isInternational;

	public Student() {
	}

	public Student(String studentNumber, String firstName, String middleName,
			String lastName, Double cgpa, LocalDate enrollmentDate,
			String isInternational) {
		this.studentNumber = studentNumber;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.cgpa = cgpa;
		this.enrollmentDate = enrollmentDate;
		this.isInternational = isInternational;
	}

	public Long getStudentId() {
		return studentId;
	}

	public void setStudentId(Long studentId) {
		this.studentId = studentId;
	}

	public String getStudentNumber() {
		return studentNumber;
	}

	public void setStudentNumber(String studentNumber) {
		this.studentNumber = studentNumber;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Double getCgpa() {
		return cgpa;
	}

	public void setCgpa(Double cgpa) {
		this.cgpa = cgpa;
	}

	public LocalDate getEnrollmentDate() {
		return enrollmentDate;
	}

	public void setEnrollmentDate(LocalDate enrollmentDate) {
		this.enrollmentDate = enrollmentDate;
	}

	public String getIsInternational() {
		return isInternational;
	}

	public void setIsInternational(String isInternational) {
		this.isInternational = isInternational;
	}
}
